from routers.auth import router as auth_router
from routers.emails import router as emails_router
from routers.rules import router as rules_router
from routers.tasks import router as tasks_router
from routers.reminders import router as reminders_router
from routers.replies import router as replies_router
from routers.dashboard import router as dashboard_router
from routers.analytics import router as analytics_router
from routers.settings import router as settings_router
from routers.ai import router as ai_router
